fix the executables list

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -43,10 +43,23 @@ jobs:
       - name: check_executables
         shell: bash
         run: |
+          find=false
           str="${{vars.EXECUTABLES}}"
           arr=($str)
+          list_file=($(ls))
+          arr_list=($list_file)
           for i in "${arr[@]}"; do
-            echo $i
+              found=false
+              for y in "${arr_list[@]}"; do
+                  if [[ "$i" == "$y" ]]; then
+                      found=true
+                      break
+                  fi
+              done
+              if ! $found; then
+                  echo "Missing executable: $i"
+                  return_value=1
+              fi
           done
   push_to_mirror:
     runs-on: ubuntu-latest
