add check executables

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -38,6 +38,10 @@ jobs:
             file=$(grep "warning" err_output | head -n1 | cut -d ":" -f1 | tr -d '\n')
             echo "::error file=$file,title=Coding style error ::Please fix it"; exit 1;
           fi
+      - name: clean_project
+        run: make clean
+      - name: check_executables
+        run: for i in ${{vars.EXECUTABLES}}; do [ -e "$i" ] || echo "::error title=The Executables are not present in the repository::Please check the compilation command before commit"; exit 1; done
   clone_to_branch:
     runs-on: ubuntu-latest
     needs: [check_remote_is_valid, check_compilation_and_coding_style]
